owner: acan3xt
repo: eddi-notifier-status

sites:
  - name: eddi-notifier
    url: https://notify.eddier.party/health

status-website:
  baseUrl: /eddi-notifier-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: eddi-notifier Status
  introTitle: "**eddi-notifier 稼働状況**"
  introMessage: eddi-notifierの稼働状況と応答時間を確認できるページです。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
